language: ruby
cache: bundler
before_install:
  - "gem update --system"
  - "gem install bundler"
rvm:
  - 2.6.3
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.2.5.0
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_6.rc1.gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.rc1.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.rc1.gemfile
script: "bundle exec rake test"
