language: ruby
cache: bundler
before_install:
  - "gem update --system"
  - "gem install bundler"
rvm:
  - 2.6.4
  - 2.5.6
  - 2.4.7
  - 2.3.8
  - jruby-9.2.8.0
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_6.rc1.gemfile
matrix:
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.rc1.gemfile
    - rvm: 2.4.7
      gemfile: gemfiles/rails_6.rc1.gemfile
script: "bundle exec rake test"
